### ISSUE TITLE
Feature Request "!add_rss"

### ISSUE THREAD

**Issue by pvyParts** [ppfeufer/aa-rss-to-discord#9]
Would be an easy way to bypass the admin site work, 

1. Install bot 
2. `!add_rss [url]`

**Comment by ppfeufer** [comment]
That is an interesting one ...

Is `allianceauth-discordbot` able to return the server name and id as well as the channel name and id of the channel that command has been issued?

**Comment by pvyParts** [comment]
the message context you get in a command has guild > channel > user > message

**Comment by ppfeufer** [comment]
Feature delivered with v1.1.0
